[AZURE]
# Connection string for Service Bus
CONNECTION_STR = Endpoint=sb://***.servicebus.windows.net/;SharedAccessKeyName=***;SharedAccessKey=***
QUEUE_NAME = test-queue
QUEUE_STATE_NAME = test-queue2

# Connection string for Blobs
STORAGE_CONNECTION_STR = DefaultEndpointsProtocol=https;AccountName=***;AccountKey=***;EndpointSuffix=core.windows.net

# Container for new data (detections/ and screenshots/ virtual folders)
BLOB_STORAGE = project-data

# Preview container
BLOB_PREVIEW = pragencies

[FILTER]
send_ok_images = False
send_billboard_images = False
send_crosswalk_damaged = False

[MODEL]
confidence_threshold = 0.56
min_percentage = 0.01

[SEGMENTATION]
# Enable crosswalk segmentation
crosswalk_segmentation_enable = False
# Minimum vehicle mask overlap with any crosswalk (10%)
overlap_threshold = 0.1
# Require overlap in at least 60% of recent frames
frame_ratio_threshold = 0.6
# Number of consecutive frames to use for overlap history
history_max_frames     = 5


[GPS]
gps_enable = True
drop_if_no_fix = True

[CAMERA]
# Set to False to use default resolution (640 x 480) or when source = video/jpg
# Set to True to apply custom resolution (e.g. 3840 x 2160, 1920 x 1080, 1707 x 960)
camera_settings_enabled = True
camera_id = 0
camera_width = 3840
camera_height = 2160

# Enable or disable cropping
camera_crop_enabled = True
camera_crop_width   = 960
camera_crop_height  = 960

# Vertical crop position (Y-axis): how far from the top the crop starts
#900, prod:600
camera_crop_y = 600

# Horizontal crop position (X-axis): how far from the left the crop starts
# You can compute it dynamically or set it manually based on your needs

# Example: Full HD (1920 x 1080)
# camera_crop_x = camera_width - camera_crop_width
#               = 1920 - 960 = 960 (centered)
# If shifted 190px to the left  1920 - 960 - 190 = 770

# Example: 4K (3840 x 2160)
# camera_crop_x = 3840 - 960 = 2880 (centered)
# If shifted 1300px to the left  3840 - 960 - 1300 = 1580
#1080, prod:1580
camera_crop_x = 1580


[DEBUG]
upload_workers = 2

show_video= False
save_video = False
save_video_path = Saved_Video
save_fps = 10
prefix_clean = Clean
prefix_annotated = Annotated